# JSON Feed
# Add "json" to the Page Kinds under [outputs] (in your site config) for which
# you want to enable JSON Feed.
[mediaTypes."application/feed+json"]
  suffixes = ["json"]
[outputFormats.json]
  name = "json"
  mediaType = "application/feed+json"
  baseName = "index" # generated file = <baseName>.<mediaType."application/feed+json".suffixes[0]> = index.json
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = false
  permalinkable = false
  root = true
